# Generated by Django 5.2.14 on 2026-05-20 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_taskcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('expected_close_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.client')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ('-created_at',),
            },
        ),
    ]
